name: bhasha_keyboard
description: "Bhasha Keyboard - Premium multilingual keyboard for 22 Indian languages with native scripts, transliteration and voice typing."
publish_to: 'none'

version: 1.1.3+7

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: 6.1.5+1
  shared_preferences: 2.5.3
  http: 1.5.0
  characters: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/stickers/
